Vagrant.configure("2") do |config|

    config.vm.box = "centos/8"
    config.vm.box_url = "https://app.vagrantup.com/centos/boxes/8"

    config.vm.define "slynellP3" do |control|

        control.vm.hostname = "slynellP3"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provision "shell", inline: <<-SHELL
        cd /etc/yum.repos.d/
        sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        sudo yum update -y
        yum install -y vim
        yum install -y net-tools
        SHELL

        control.vm.provider "virtualbox" do |v|
            v.name = "slynellP3"
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.memory = 10000
            v.cpus = 2
        end
    end
end